name: upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ID }}
          r2-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.BUCKET }}
          source-dir: scripts
          destination-dir: scripts